export const INICIAR_CARGA = 'INICIAR_CARGA';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_LIBROS = 'OBTENER_LIBROS';
export const OBTENER_INFORMACION_LIBRO = 'OBTENER_INFORMACION_LIBRO';
export const OBTENER_LIBROS_CATEGORIA = 'OBTENER_LIBROS_CATEGORIA';
export const AGREGAR_LIBRO = 'AGREGAR_LIBRO';
export const EDITAR_LIBRO = 'EDITAR_LIBRO';
export const AGREGAR_VALORACION = 'AGREGAR_VALORACION';
export const AGREGAR_LISTA_DESEOS = 'AGREGAR_LISTA_DESEOS';
// export const ELIMINAR_LISTA_DESEOS = 'ELIMINAR_LISTA_DESEOS';
export const ELIMINAR_LIBRO = 'ELIMINAR_LIBRO';

export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const EDITAR_CATEGORIA = 'EDITAR_CATEGORIA';
export const ELIMINAR_CATEGORIA = 'ELIMINAR_CATEGORIA';

export const OBTENER_AUTORES = 'OBTENER_AUTORES';
export const AGREGAR_AUTOR = 'AGREGAR_AUTOR';
export const EDITAR_AUTOR = 'EDITAR_AUTOR';
export const ELIMINAR_AUTOR = 'ELIMINAR_AUTOR';

export const OBTENER_EDITORIALES = 'OBTENER_EDITORIALES';
export const AGREGAR_EDITORIAL = 'AGREGAR_EDITORIAL';
export const EDITAR_EDITORIAL = 'EDITAR_EDITORIAL';
export const ELIMINAR_EDITORIAL = 'ELIMINAR_EDITORIAL';

export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';

export const OBTENER_ROLES = 'OBTENER_ROLES';
export const AGREGAR_ROL = 'AGREGAR_ROL';
export const EDITAR_ROL = 'EDITAR_ROL';
export const ELIMINAR_ROL = 'ELIMINAR_ROL';

export const OBTENER_LIBROS_CARRITO = 'OBTENER_LIBROS_CARRITOS';
export const AGREGAR_LIBRO_CARRITO = 'AGREGAR_LIBRO_CARRITO';
export const EDITAR_CANTIDAD_LIBRO = 'EDITAR_CANTIDAD_LIBRO';
export const ELIMINAR_LIBRO_CARRITO = 'ELIMINAR_LIBRO_CARRITO';